### ISSUE TITLE
Add member counts on guild list

### ISSUE THREAD

**Issue by fbrettnich** [discordlookup/discordlookup#7]
Preview:
![guild-list-member-counts-preview](https://user-images.githubusercontent.com/42101045/177139789-bd7c2a79-c9ee-4b2c-99ac-4fc4a8080556.png)

**Comment by Mark2051** [comment]
cool

**Comment by fbrettnich** [comment]
Implemented with commit https://github.com/discordlookup/discordlookup/commit/fa1b39545e1cad1600313875b2cd378a703ee172
